### ISSUE TITLE
Sometimes the OVS switch is not properly configured with leaf port at startup

### ISSUE THREAD

**Issue by renatof** [EdgeVPNio/evio#2]

**Comment by renatof** [comment]
One symptom of this issue is that the Evio switch is up and tunnels are formed, but packets are not picked from the virtual network interface (e.g. a node is not able to ping other nodes).

If you notice your node is not able to send packets on the network, check the output of the following command:
grep DPSet /var/log/edge-vpnio/bf.log 

If the output shows an empty set under port_state:
0915 10:55:39.469 INFO: DPSet.port_state {}

Until this issue is fixed, the only solution is to restart the virtual network in the affected node(s): 
systemctl restart evio

**Comment by kcratie** [comment]
Fixed in v20.12.2
