### ISSUE TITLE
Not an ISSUE, Querries

### ISSUE THREAD

**Issue by PPBRD** [EdgeVPNio/evio#30]
How many max tunnels can a single center location can support, is there any restrictions?

Thanks and regards
Bharat

**Comment by kcratie** [comment]
Hello Bharat, 
The EngeVPN controller automatically manages the number of tunnels at each node to limit the load imposed on the host. However, you can explicitly override this in the configuration file [https://github.com/EdgeVPNio/evio/blob/master/controller/template-config.json#L32] by setting custom values for MaxSuccessors, MaxLongDistEdges, and MaxOnDemandEdges. See https://edgevpn.io/configfile/ for details. I would suggest first increasing MaxOnDemandEdges to determine if that suits your needs.

Feel welcome to join our EdgeVPN discussion group at https://groups.io/g/EdgeVPN.

Regards,
ken
