### ISSUE TITLE
Is there a way to install a Bootstrap Server without using Docker?

### ISSUE THREAD

**Issue by bmullan** [EdgeVPNio/evio#31]
I use Ubuntu 22.04 LTS on my systems and LXD "_system_" Containers and LXD VMs.

Although I can run and do run Docker "nested" in my LXD containers and could create a  Bootstrap Server doing that.

However, I'd prefer not to duplicate Container functionality and would rather just use an LXD Container to create a EdgeVPN Bootstap Server.

Is this possible?

thanks for any info.

brian

**Comment by kcratie** [comment]
Yes, you can. There is no restriction on how to deploy the XMPP server necessary for bootstrapping evio tunnels. Setup ejabberd, Openfire or any other XMMP server, and optionally coturn, on metal, VM, container, in cloud or your local LAN. The server addresses will need to be addressable endpoints for all the evio nodes.
