### ISSUE TITLE
Automated tests for evio

### ISSUE THREAD

**Issue by pradeeban** [EdgeVPNio/evio#32]
This is part of https://github.com/openjournals/joss-reviews/issues/6638 review.

While automated tests are not mandatory and manual steps are okay as part of the JOSS review ("Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?"), given the complex nature of the project, automated tests to confirm the framework installs and works (through a set of test cases) will be a great addition.

Is this possible to be incorporated (or is this something that already exists and I did not look careful enough)?

**Comment by kcratie** [comment]
The software source code and release package are both open source and freely available in the evio and tincan repositories. Running Evio requires external services for authentication and signaling, and we have hosted this service as a convenience to the JOSS reviewers for demonstrating Evio. An archive containing the configuration files for accessing our hosted services has been attached to our review thread #6638. Instructions for getting started with EdgeVPN are available [here](https://edgevpn.io/trial/).
